config/routes.rb
Rails.application.routes.draw do
  root to: 'quiz#question'
  get 'quiz', to: 'quiz#question'
  post 'quiz', to: 'quiz#answer'
  resources :questions
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_one :answer, dependent: :destroy
  accepts_nested_attributes_for :answer

  validates :content_html, presence: true

  # For XSS
  validates :content_html, format: { without: /<script>/ }
  validates :content_html, format: { without: /<\/script>/ }
  validates :content_html, format: { without: /javascript:/ }

  validates_associated :answer

  CONTENT_HTML_TRUNCATE_LENGTH = 50

  def is_correct?(answer)
    normalize!(self.answer.content) == normalize!(answer)
  end

  private
    def normalize!(str)
      str_array = str.downcase.strip.squish.split(' ')
      str_array.each_with_index do |value, index|
        humanized = value.humanize
        str_array[index] = Utils::IntegerToEn.to_en!(humanized.to_i) if is_integer?(humanized)
      end
      str_array.join(' ')
    end

    def is_integer?(str)
      str =~ /\A[1-9][0-9]*\z/
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.build_answer
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        flash[:success] = 'Question was successfully created.'
        format.html { redirect_to @question }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        flash[:success] = 'Question was successfully updated.'
        format.html { redirect_to @question }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      flash[:success] = 'Question was successfully destroyed.'
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content_html, answer_attributes: [:id, :question_id, :content])
    end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  before_action :set_random_question, only: [:question]
  before_action :set_question, only: [:answer]

  # GET /quiz
  def question
  end

  # POST /quiz
  def answer
    respond_to do |format|
      if @question.is_correct?(quiz_params[:answer])
        flash.now[:success] = 'Correct'
        format.html { render :answer }
      else
        flash.now[:alert] = 'Incorrect'
        format.html { render :answer }
      end
    end
  end

  private
    def quiz_params
      params.require(:quiz).permit(:question_id, :answer)
    end

    def set_random_question
      @question = Question.all.sample(1).first
    end

    def set_question
      @question = Question.find(quiz_params[:question_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then
      'alert alert-info'
    when 'success' then
      'alert alert-success'
    when 'error' then
      'alert alert-danger'
    when 'alert' then
      'alert alert-danger'
    else
      'alert alert-info'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'QuizMaster', root_path, {:class => "navbar-brand"} %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav  mr-auto">
      <li class="nav-item<%= ' active' if controller.controller_name == 'quiz' %>">
        <%= link_to 'Quiz Mode', quiz_path, {:class => "nav-link"} %>
      </li>
      <li class="nav-item<%= ' active' if controller.controller_name == 'questions' %>">
        <%= link_to 'Manage Question', questions_path, {:class => "nav-link"} %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMaster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content_html %>
    <%= form.text_area :content_html, {:class => 'form-control'} %>
  </div>

  <%= form.fields_for :answer do |a| %>
    <div class="form-group">
      <%= a.label :content, 'Answer' %>
      <%= a.text_area :content, {:class => 'form-control'} %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question, {:class => 'btn btn-info'} %>
<%= link_to 'Back', questions_path, {:class => 'btn btn-secondary'} %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<%= render 'shared/flash' %>

<div class="mb-3">
  <%= link_to 'New Question', new_question_path, {:class => 'btn btn-primary'} %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Content Html</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.content_html.truncate(Question::CONTENT_HTML_TRUNCATE_LENGTH) %></td>
        <td>
          <% if question.answer.present? %>
            <%= question.answer.content %>
          <% else %>
            -
          <% end %>
        </td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path, {:class => 'btn btn-secondary'} %>

app/views/questions/show.html.erb
<h1>Show Question</h1>

<%= render 'shared/flash' %>

<p>
  <strong>ID:</strong>
  <%= @question.id %>
</p>

<p>
  <strong>Content Html:</strong>
  <%= @question.content_html %>
</p>

<p>
  <strong>Answer:</strong>
  <% if @question.answer.present?%>
    <%= @question.answer.content %>
  <% else %>
    -
  <% end %>
</p>

<%= link_to 'Edit', edit_question_path(@question), {:class => 'btn btn-info'} %>
<%= link_to 'Back', questions_path, {:class => 'btn btn-secondary'} %>

app/views/quiz/answer.html.erb
<h1>Quiz Mode</h1>

<%= render 'shared/flash' %>

<h2>Qustion</h2>

<div class="mb-3">
  <%== @question.content_html %>
</div>

<h2>Answer</h2>

<div class="mb-3">
  <%== @question.answer.content %>
</div>

<div class="mb-3">
  <%= link_to 'Next Quiz', quiz_path, {:class => 'btn btn-primary'} %>
</div>

app/views/quiz/question.html.erb
<h1>Quiz Mode</h1>

<%= render 'shared/flash' %>

<div class="mb-3">
  <%== @question.content_html %>
</div>

<%= form_with(url: quiz_path, method: :post, scope: :quiz, local: true) do |form| %>
  <%= hidden_field_tag 'quiz[question_id]', @question.id %>

  <div class="form-group">
    <%= form.text_area :answer, {:class => 'form-control', :placeholder => 'Please enter the Answer'} %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>
<% end %>